BlogApp/Controllers/CategoryController.cs
using BlogApp.Data.Abstract;
using BlogApp.Data.Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BlogApp.Controllers
{   
    [Authorize ( Roles = "Admin")]
    public class CategoryController : Controller
    {
        private ICategoryRepository _categoryRepository;
        public CategoryController(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }
        public IActionResult Index()
        {
            return View(_categoryRepository.GetAllCategories());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Category category)
        {
            _categoryRepository.AddCategory(category);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {

            _categoryRepository.DeleteCategory(id);
            return RedirectToAction("Index");
        }
    }
}

BlogApp/Controllers/PostController.cs
using BlogApp.Data.Abstract;
using BlogApp.Data.Entity;
using BlogApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using BlogApp.Data.Concrete;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace BlogApp.Controllers;

public class PostController : Controller
{
    private readonly IPostRepository _postRepository;

    private readonly UserManager<BlogAppUser> _userManager;

    private readonly ICategoryRepository _categoryRepository;

    public PostController(IPostRepository postRepository, UserManager<BlogAppUser> userManager, ICategoryRepository categoryRepository)
    {
        _postRepository = postRepository;
        _userManager = userManager;
        _categoryRepository = categoryRepository;
    }


    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> List()
    {
        var posts = await _postRepository.GetAllPosts().Where(p => p.IsPublished)
            .Include(p => p.Writer) // Yazar bilgilerini dahil et
            .Include(p => p.Category) // Kategori bilgilerini dahil et
            .ToListAsync();
        return View(posts);
    }


    public async Task<IActionResult> Details(int id)
    {
        var post = await _postRepository.GetAllPosts()
            .Include(p => p.Writer).Include(p => p.Comments).ThenInclude(c => c.Writer).Include(p => p.Favorites)
            .FirstOrDefaultAsync(p => p.PostId == id);

        if (post == null)
        {
            return NotFound();
        }

        return View(post);
    }
    public async Task<IActionResult> Index(string? category, string? search)
    {
        var posts = await _postRepository.GetAllPosts()
            .Where(p => p.IsPublished)
            .Include(p => p.Writer)
            .Include(p => p.Category)
            .ToListAsync();

        if (!string.IsNullOrEmpty(category))
        {
            posts = posts.Where(p => p.Category.Name == category).ToList();
        }

        if (!string.IsNullOrEmpty(search))
        {
            posts = posts.Where(p => p.Title.Contains(search) || p.Content.Contains(search)).ToList();
        }

        var model = new PostViewModel
        {
            Posts = posts,
            Search = search
        };

        return View(model);
    }

    [Authorize]
    [HttpGet]
    public IActionResult Create()
    {
        ViewBag.Categories = new SelectList(_categoryRepository.GetAllCategories(), "CategoryId", "Name");
        return View();
    }

    [Authorize]
    [HttpPost]
    public async Task<IActionResult> Create(PostViewModel model)
    {
        if (ModelState.IsValid)
        {
            string? imageUrl = null;

            if (model.Image != null)
            {
                var fileName = Path.GetRandomFileName() + Path.GetExtension(model.Image.FileName);
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", fileName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await model.Image.CopyToAsync(stream);
                }
                imageUrl = "/images/" + fileName;
            }
            var post = new Post
            {
                Title = model.Title,
                Content = model.Content,
                Description = model.Description,
                CreatedAt = DateTime.Now,
                UpdatedAt = DateTime.Now,
                IsPublished = true,
                ImageUrl = imageUrl,
                WriterId = User.FindFirstValue(ClaimTypes.NameIdentifier),
                CategoryId = model.CategoryId
            };
            _postRepository.AddPost(post);

            return RedirectToAction("Index");
        }
        return View(model);
    }

    [Authorize]
    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        var post = await _postRepository.GetPostById(id);
        if (post == null)
        {
            return NotFound();
        }

        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        var user = await _userManager.FindByIdAsync(userId);

        if (user == null || (post.WriterId != userId && !await _userManager.IsInRoleAsync(user, "Admin")))
        {
            return Forbid();
        }

        ViewBag.Categories = new SelectList(_categoryRepository.GetAllCategories(), "CategoryId", "Name", post.CategoryId);
        var model = new PostViewModel
        {
            Id = post.PostId,
            Title = post.Title,
            Description = post.Description,
            Content = post.Content,
            ImageUrl = post.ImageUrl,
        };

        return View(model);
    }

    [Authorize]
    [HttpPost]
    public async Task<IActionResult> Edit(PostViewModel model)
    {
        if (ModelState.IsValid)
        {
            var post = await _postRepository.GetPostById(model.Id);
            if (post == null)
            {
                return NotFound();
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await _userManager.FindByIdAsync(userId);

            if (user == null || (post.WriterId != userId && !await _userManager.IsInRoleAsync(user, "Admin")))
            {
                return Forbid();
            }

            post.Title = model.Title;
            post.Description = model.Description;
            post.Content = model.Content;
            post.UpdatedAt = DateTime.Now;
            post.CategoryId = model.CategoryId;

            if (model.Image != null)
            {
                var fileName = Path.GetRandomFileName() + Path.GetExtension(model.Image.FileName);
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", fileName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await model.Image.CopyToAsync(stream);
                }
                post.ImageUrl = "/images/" + fileName;
            }

            _postRepository.UpdatePost(post);

            return RedirectToAction("Details", new { id = post.PostId });
        }

        return View(model);
    }

    [Authorize]
    [HttpGet]
    public async Task<IActionResult> Delete(int id)
    {
        var post = await _postRepository.GetPostById(id);
        if (post == null)
        {
            return NotFound();
        }

        _postRepository.DeletePost(id);
        return Redirect(Request.Headers["Referer"].ToString());
    }


}

BlogApp/Controllers/RolesController.cs
using BlogApp.Data.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BlogApp.Controllers;

[Authorize (Roles = "Admin")]
public class RolesController:Controller
{   
    private readonly RoleManager<BlogAppRole> _roleManager;
    private readonly UserManager<BlogAppUser> _userManager;

    public RolesController(RoleManager<BlogAppRole> roleManager,UserManager<BlogAppUser> userManager)
    {
        _roleManager = roleManager;
        _userManager = userManager;


    }
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            var roleUsers = new Dictionary<string, List<string>>();
            foreach (var role in roles)
            {
                var usersInRole = await _userManager.GetUsersInRoleAsync(role.Name);
                roleUsers[role.Id] = usersInRole.Select(u => u.UserName).ToList();
            }

            ViewBag.RoleUsers = roleUsers;
            return View(roles);
        }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> Create(BlogAppRole model)
    {   
        if(ModelState.IsValid)
        {        
        IdentityResult result = await _roleManager.CreateAsync(model);
        if (result.Succeeded)
        {
            return RedirectToAction("Index");
        }
        else
        {
            foreach (IdentityError error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
        }
        return View(model);

        }
        return View(model);

    }

    [HttpGet]
    public async Task<IActionResult> Edit(string id)
    {   
        BlogAppRole role = await _roleManager.FindByIdAsync(id);
        if (role != null)
        {   
                var usersInRole = await _userManager.GetUsersInRoleAsync(role.Name);
                ViewBag.Users = usersInRole;
            return View(role);
        }
        return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<IActionResult> Edit(BlogAppRole model)
    {
        if (ModelState.IsValid)
        {
            IdentityResult result = await _roleManager.UpdateAsync(model);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            else
            {
                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
        }
        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> Delete(string id)
    {
        BlogAppRole role = await _roleManager.FindByIdAsync(id);
        if (role != null)
        {
            IdentityResult result = await _roleManager.DeleteAsync(role);
        }
        return RedirectToAction("Index");
    }
}

BlogApp/Controllers/UsersController.cs
using BlogApp.Data.Concrete;
using BlogApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BlogApp.Controllers
{   [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly UserManager<BlogAppUser> _userManager;

        private readonly RoleManager<BlogAppRole> _roleManager;

        public UsersController(UserManager<BlogAppUser> userManager,RoleManager<BlogAppRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            return View(_userManager.Users);
        }

        public IActionResult Create()
        {
            return View();
        }

        [Authorize  (Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new BlogAppUser
                {
                    UserName = model.UserName,
                    Name = model.Name,
                    Surname = model.Surname
                    
                };

                var result = await _userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return View(model);
        }

        [Authorize (Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            else{

            ViewBag.Roles = await _roleManager.Roles.Select(r => r.Name).ToListAsync();


            var model = new EditUserViewModel
            {
                Id = user.Id,
                UserName = user.UserName,
                SelectedRoles = await _userManager.GetRolesAsync(user)

            };



            return View(model);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(model.Id);
                if (user == null)
                {
                    return NotFound();
                }

                user.UserName = model.UserName;

                var result = await _userManager.UpdateAsync(user);

                if (result.Succeeded)
                {                       
                    await _userManager.RemoveFromRolesAsync(user, await _userManager.GetRolesAsync(user));
                    if (model.SelectedRoles != null)
                    {
                    await _userManager.AddToRolesAsync(user, model.SelectedRoles);
                    }
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                var result = await _userManager.DeleteAsync(user);
            }

            return RedirectToAction("Index");
        }


    }
}

BlogApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/css/custom-theme.css" />
</head>

<body>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm mb-4">
            <div class="container">
                <a class="navbar-brand text-primary font-weight-bold" asp-area="" asp-controller="Post"
                    asp-action="Index">BlogApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users"
                                asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Roles"
                                asp-action="Index">Roles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="List">Posts</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category"
                                asp-action="Index">Categories</a>
                        </li>
                        }
                    </ul>
                    <ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                         @await Component.InvokeAsync("Notifications")

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="Index"
                                asp-route-userName="@User.Identity.Name">@User.Identity.Name</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account"
                                asp-action="Logout">Logout</a>
                        </li>
                        }
                        else
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account"
                                asp-action="Login">Login</a>
                        </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container content">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="bg-light text-center text-dark border-top pt-3 pb-3 mt-4">
        <div class="container">
            &copy; @DateTime.Now.Year - BlogApp
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>