BlogApp/ViewModels/PostViewModel.cs
using BlogApp.Data.Entity;

namespace BlogApp.ViewModels
{
    public class PostViewModel
    {   
        public int Id { get; set; }
        public string Title { get; set; } = null!;
        public string Content { get; set; } = null!;
        public string Description { get; set; } = null!;
        public List<Post>? Posts { get; set; }

        public IFormFile? Image { get; set; }

        public string? ImageUrl { get; set; }

        public int? CategoryId { get; set; }

        public string? Search { get; set; }
    }
}

BlogApp/Controllers/FavoritesController.cs
using System.Security.Claims;
using BlogApp.Data.Abstract;
using BlogApp.Data.Entity;
using Microsoft.AspNetCore.Mvc;

namespace BlogApp.Controllers;

public class FavoritesController : Controller
{

    readonly IFavoriteRepository _favoriteRepository;
    readonly INotificationRepository _notificationRepository;

    public FavoritesController(IFavoriteRepository favoriteRepository, INotificationRepository notificationRepository)
    {
        _favoriteRepository = favoriteRepository;
        _notificationRepository = notificationRepository;
    }

    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> AddFavorite(int postId)
    {
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        if (userId == null)
        {
            return RedirectToAction("Login", "Account");
        }

        var favorite = new Favorite
        {
            PostId = postId,
            UserId = userId,
            CreatedAt = DateTime.Now,
        };

        _favoriteRepository.AddFavorite(favorite);

        var post = _favoriteRepository.GetPostByFavoriteId(favorite.FavoriteId);
        if (post != null)
        {
            // Bildirim oluştur
            await _notificationRepository.CreateNotificationAsync(post.WriterId, userId, "favorited your post", postId);
        }

        return RedirectToAction("Details", "Post", new { id = postId });
    }

    [HttpPost]
    public async Task<IActionResult> RemoveFavorite(int postId)
    {
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        if (userId == null)
        {
            return RedirectToAction("Login", "Account");
        }

        var favorite = await _favoriteRepository.GetFavoriteAsync(userId, postId);
        if (favorite != null)
        {
            _favoriteRepository.DeleteFavorite(favorite.FavoriteId);
            Console.WriteLine("Favorite deleted");
        }

        return RedirectToAction("Details", "Post", new { id = postId });
    }
}

BlogApp/Controllers/PostController.cs
using BlogApp.Data.Abstract;
using BlogApp.Data.Entity;
using BlogApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using BlogApp.Data.Concrete;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace BlogApp.Controllers;

public class PostController : Controller
{
    private readonly IPostRepository _postRepository;

    private readonly UserManager<BlogAppUser> _userManager;

    private readonly ICategoryRepository _categoryRepository;

    public PostController(IPostRepository postRepository, UserManager<BlogAppUser> userManager, ICategoryRepository categoryRepository)
    {
        _postRepository = postRepository;
        _userManager = userManager;
        _categoryRepository = categoryRepository;
    }


    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> List()
    {
        var posts = await _postRepository.GetAllPosts().Where(p => p.IsPublished)
            .Include(p => p.Writer) // Yazar bilgilerini dahil et
            .Include(p => p.Category) // Kategori bilgilerini dahil et
            .ToListAsync();
        return View(posts);
    }


    public async Task<IActionResult> Details(int id)
    {
        var post = await _postRepository.GetAllPosts()
            .Include(p => p.Writer).Include(p => p.Comments).ThenInclude(c => c.Writer).Include(p => p.Favorites)
            .FirstOrDefaultAsync(p => p.PostId == id);

        if (post == null)
        {
            return NotFound();
        }

        return View(post);
    }
    public async Task<IActionResult> Index(string? category, string? search)
    {
        var posts = await _postRepository.GetAllPosts()
            .Where(p => p.IsPublished)
            .Include(p => p.Writer)
            .Include(p => p.Category)
            .ToListAsync();

        if (!string.IsNullOrEmpty(category))
        {
            posts = posts.Where(p => p.Category.Name == category).ToList();
        }

        if (!string.IsNullOrEmpty(search))
        {
            posts = posts.Where(p => p.Title.Contains(search) || p.Content.Contains(search)).ToList();
        }

        var model = new PostViewModel
        {
            Posts = posts,
            Search = search
        };

        return View(model);
    }

    [Authorize]
    [HttpGet]
    public IActionResult Create()
    {
        ViewBag.Categories = new SelectList(_categoryRepository.GetAllCategories(), "CategoryId", "Name");
        return View();
    }

    [Authorize]
    [HttpPost]
    public async Task<IActionResult> Create(PostViewModel model)
    {
        if (ModelState.IsValid)
        {
            string? imageUrl = null;

            if (model.Image != null)
            {
                var fileName = Path.GetRandomFileName() + Path.GetExtension(model.Image.FileName);
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", fileName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await model.Image.CopyToAsync(stream);
                }
                imageUrl = "/images/" + fileName;
            }
            var post = new Post
            {
                Title = model.Title,
                Content = model.Content,
                Description = model.Description,
                CreatedAt = DateTime.Now,
                UpdatedAt = DateTime.Now,
                IsPublished = true,
                ImageUrl = imageUrl,
                WriterId = User.FindFirstValue(ClaimTypes.NameIdentifier),
                CategoryId = model.CategoryId
            };
            _postRepository.AddPost(post);

            return RedirectToAction("Index");
        }
        return View(model);
    }

    [Authorize]
    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        var post = await _postRepository.GetPostById(id);
        if (post == null)
        {
            return NotFound();
        }

        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        var user = await _userManager.FindByIdAsync(userId);

        if (user == null || (post.WriterId != userId && !await _userManager.IsInRoleAsync(user, "Admin")))
        {
            return Forbid();
        }

        ViewBag.Categories = new SelectList(_categoryRepository.GetAllCategories(), "CategoryId", "Name", post.CategoryId);
        var model = new PostViewModel
        {
            Id = post.PostId,
            Title = post.Title,
            Description = post.Description,
            Content = post.Content,
            ImageUrl = post.ImageUrl,
        };

        return View(model);
    }

    [Authorize]
    [HttpPost]
    public async Task<IActionResult> Edit(PostViewModel model)
    {
        if (ModelState.IsValid)
        {
            var post = await _postRepository.GetPostById(model.Id);
            if (post == null)
            {
                return NotFound();
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await _userManager.FindByIdAsync(userId);

            if (user == null || (post.WriterId != userId && !await _userManager.IsInRoleAsync(user, "Admin")))
            {
                return Forbid();
            }

            post.Title = model.Title;
            post.Description = model.Description;
            post.Content = model.Content;
            post.UpdatedAt = DateTime.Now;
            post.CategoryId = model.CategoryId;

            if (model.Image != null)
            {
                var fileName = Path.GetRandomFileName() + Path.GetExtension(model.Image.FileName);
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", fileName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await model.Image.CopyToAsync(stream);
                }
                post.ImageUrl = "/images/" + fileName;
            }

            _postRepository.UpdatePost(post);

            return RedirectToAction("Details", new { id = post.PostId });
        }

        return View(model);
    }

    [Authorize]
    [HttpGet]
    public async Task<IActionResult> Delete(int id)
    {
        var post = await _postRepository.GetPostById(id);
        if (post == null)
        {
            return NotFound();
        }

        _postRepository.DeletePost(id);
        return Redirect(Request.Headers["Referer"].ToString());
    }


}

BlogApp/Views/Post/Create.cshtml
@model BlogApp.ViewModels.PostViewModel

@{
    ViewData["Title"] = "Create Post";
}
<h2>Create Post</h2>
<hr>
<form asp-controller="Post" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="All" class="text-danger mb-3"></div>

    <!-- Title Field -->
    <div class="mb-3">
        <label asp-for="Title" class="form-label">Title</label>
        <input asp-for="Title" class="form-control" placeholder="Enter the post title" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>

    <!-- Description Field -->
    <div class="mb-3">
        <label asp-for="Description" class="form-label">Description</label>
        <input asp-for="Description" class="form-control" placeholder="Enter a short description" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <!-- Content Field with CKEditor -->
    <div class="mb-3">
        <label asp-for="Content" class="form-label">Content</label>
        <textarea asp-for="Content" class="form-control" id="editor" placeholder="Write the content of the post"></textarea>
        <span asp-validation-for="Content" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="CategoryId" class="form-label">Category</label>
        <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.Categories">
            <option value="">Select a category</option>
        </select>
        <span asp-validation-for="CategoryId" class="text-danger"></span>
    </div>

    <!-- Image Upload -->
    <div class="mb-3">
        <label asp-for="Image" class="form-label">Upload Image</label>
        <input asp-for="Image" class="form-control" type="file" />
        <span asp-validation-for="Image" class="text-danger"></span>
    </div>

    <!-- Submit Button -->
    <div class="mb-3">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>


</form>



@section Scripts {
    <!-- CKEditor Script -->
    <script src="https://cdn.ckeditor.com/ckeditor5/39.0.1/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#editor'))
            .catch(error => {
                console.error(error);
            });
    </script>
}

BlogApp/Views/Post/Details.cshtml
@using System.Security.Claims
@model BlogApp.Data.Entity.Post

@inject BlogApp.Data.Abstract.IFavoriteRepository FavoriteRepository
@{
    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
    var isFavorite = FavoriteRepository.GetFavoriteAsync(userId, Model.PostId).Result != null;
}

@{
    ViewData["Title"] = Model.Title;
}

<div class="row">
    <div class="col-lg-8">
        <div class="bg-white shadow-sm rounded p-4 mb-4">
            <h1 class="h3 mb-4 text-primary">@Model.Title</h1>
            <img src="@Model.ImageUrl" class="img-fluid rounded mb-3" alt="Post Image">
            <ul class="list-inline my-3 text-muted">
                <li class="list-inline-item"><i class="bi bi-calendar"></i> Created At: @Model.CreatedAt.ToString("d")</li>
                <li class="list-inline-item"><i class="bi bi-person-circle"></i> <a asp-controller="Profile" asp-action="Index" asp-route-userName="@Model.Writer?.UserName" class="text-decoration-none">@Model.Writer?.Name @Model.Writer?.Surname</a></li> 
                <li class="list-inline-item"><i class="bi bi-chat-dots"></i> @Model.Comments?.Count()</li>
                <li class="list-inline-item"><i class="bi bi-heart"></i> @Model.Favorites?.Count()</li>
            </ul>
            <hr class="my-4">
            <div class="mt-4">
                @Html.Raw(@Model.Content)
            </div>
            <hr class="my-4">
            <div>
                @if (isFavorite)
                {
                    <form asp-controller="Favorites" asp-action="RemoveFavorite" method="post"> 
                        <input type="hidden" name="postId" value="@Model.PostId" />
                        <button type="submit" class="btn btn-outline-danger">
                            <i class="bi bi-heart-fill"></i> Favorilerden Kaldır
                        </button>
                    </form>
                }
                else
                {
                    <form asp-controller="Favorites" asp-action="AddFavorite" method="post">
                        <input type="hidden" name="postId" value="@Model.PostId" />
                        <button type="submit" class="btn btn-outline-primary">
                            <i class="bi bi-heart"></i> Favorilere Ekle
                        </button>
                    </form>
                }
            </div>
        </div>

        <!-- Comments Section -->
        <div class="bg-light p-4 rounded">
            <div class="card border-0">
                <div class="card-header pb-0">
                    <h4 class="mb-0">@Model.Comments?.Count() adet yorum</h4>
                </div>

                <div class="card-body">
                    @foreach (var comment in Model.Comments)
                    {
                        <div class="card mb-3 shadow-sm">
                            <div class="card-body d-flex">
                                <!-- Profile Image -->
                                <div class="me-3">
                                    @if (!string.IsNullOrEmpty(comment.Writer?.ProfileImageUrl))
                                    {
                                        <img src="@comment.Writer.ProfileImageUrl" class="img-fluid rounded-circle" style="width: 50px; height: 50px;" alt="Profile Image">
                                    }
                                    else
                                    {
                                        <img src="/images/default-profile.png" class="img-fluid rounded-circle" style="width: 50px; height: 50px;" alt="Default Profile Image">
                                    }
                                </div>

                                <!-- Comment Content -->
                                <div>
                                    <a asp-controller="Profile" asp-action="Index" asp-route-userName="@comment.Writer.UserName">
                                        <h5 class="card-title">@comment.Writer.Name @comment.Writer.Surname</h5>
                                    </a>
                                    <p class="card-text">@comment.CommentText</p>
                                    <p class="card-text"><small class="text-muted">@comment.CreatedAt.ToString("d")</small></p>
                                </div>
                            </div>
                        </div>
                    }

                    <!-- Add Comment Section -->
                    <div class="mt-4">
                        <h4 class="mb-3">Yorum Ekle</h4>
                        <form method="post" action="/Comments/Create">
                            <input type="hidden" name="PostId" value="@Model.PostId">
                            @Html.AntiForgeryToken()

                            <div class="mb-3">
                                <label for="Text" class="form-label">Yorum</label>
                                <textarea type="text" class="form-control" id="CommentText" rows="3" name="CommentText"></textarea>
                            </div>
                            <div class="mb-3">
                                <button type="submit" class="btn btn-primary">Kaydet</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Sidebar with New Posts -->
    <div class="col-lg-4">
        <vc:new-posts></vc:new-posts>
    </div>
</div>

BlogApp/Views/Post/Edit.cshtml
@model BlogApp.ViewModels.PostViewModel

@{
    ViewData["Title"] = "Edit Post";
}

<h2>Edit Post</h2>
<hr>
<form asp-controller="Post" asp-action="Edit" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="mb-3">
        <label asp-for="Title" class="control-label"></label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Description" class="control-label"></label>
        <input asp-for="Description" class="form-control"></input>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Content" class="control-label"></label>
        <textarea asp-for="Content" class="form-control" id="editor"></textarea>
        <span asp-validation-for="Content" class="text-danger"></span>
    </div>
    
    <div class="mb-3">
        <label asp-for="CategoryId" class="form-label">Category</label>
        <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.Categories">
            <option value="">Select a category</option>
        </select>
        <span asp-validation-for="CategoryId" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Image" class="control-label"></label>
        <input asp-for="Image" class="form-control" type="file" />
        <span asp-validation-for="Image" class="text-danger"></span>
    </div>
    @if (!string.IsNullOrEmpty(Model.ImageUrl))
    {
        <div class="mb-3">
            <label>Current Image</label>
            <div>
                <img src="@Model.ImageUrl" class="img-fluid rounded" alt="Current Image" style="max-width: 200px;" />
            </div>
        </div>
    }



    <div class="mb-3">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>


@section Scripts {
    <!-- CKEditor Script -->
    <script src="https://cdn.ckeditor.com/ckeditor5/39.0.1/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#editor'))
            .catch(error => {
                console.error(error);
            });
    </script>
}

BlogApp/Views/Post/Index.cshtml
@model BlogApp.ViewModels.PostViewModel


@{
    ViewData["Title"] = "Posts";
}
@if (User.Identity.IsAuthenticated)
{
    <div class="mb-3">
        <a asp-controller="Post" asp-action="Create" class="btn btn-primary">
            <i class="bi bi-plus-circle"></i> Yeni Blog Yayınla
        </a>
    </div>
}
else
{
    <div class="alert alert-warning" role="alert">
        To publish a blog, please <a href="/Account/Login" class="alert-link">log in</a> or <a href="/Account/Register" class="alert-link">register</a>.
    </div>
}



<div class="container mt-4">

    <form asp-action="Index" method="get" class="mb-4">
        <div class="input-group">
            <input type="text" name="search" class="form-control" placeholder="Search by title" value="@ViewData["CurrentFilter"]" />
            <button class="btn btn-primary" type="submit">Search</button>
        </div>
    </form>
    <div class="row">
        <!-- Ana Postlar -->
        <div class="col-lg-8">
            <h1 class="h4 mb-4 text-primary fw-bold">Posts</h1>
            <div class="bg-white p-4 rounded shadow-sm">
                
                @foreach (var post in Model.Posts)
                {
                    <div class="card border-0 mb-4">
                        <div class="row g-0">
                            <!-- Post Görseli -->
                            <div class="col-md-4">
                                <img src="@post.ImageUrl" class="img-fluid rounded-start" alt="Post Image">
                            </div>
                            <!-- Post İçeriği -->
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h5 class="card-title">
                                        <a href="/Post/Details/@post.PostId" class="text-decoration-none text-dark fw-bold">
                                            @post.Title
                                        </a>
                                    </h5>
                                    <p class="card-text text-muted">@post.Description</p>
                                    <p class="mt-2">
                                        <a asp-action="Index" asp-route-category="@post.Category?.Name" class="badge bg-danger bg-opacity-10 text-danger fw-bold">@post.Category?.Name</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr class="my-4">
                }
            </div>
        </div>

        <!-- Yan Menü -->
        <div class="col-lg-4">
            <div class="bg-white p-4 rounded shadow-sm">
                @await Component.InvokeAsync("CategoryFilter")
            </div>
            <div class="bg-white p-4 rounded shadow-sm mb-4">
                @await Component.InvokeAsync("NewPosts")
            </div>




        </div>
    </div>
</div>

BlogApp/Views/Post/List.cshtml
@model IEnumerable<BlogApp.Data.Entity.Post>

@{
    ViewData["Title"] = "Post List";
}

    <div class="container mt-4">
        <h2 class="text-primary mb-4">Post List</h2>
    
        <a class="btn btn-success mb-3" asp-controller="Post" asp-action="Create">
            <i class="fas fa-plus-circle"></i> Create New Post
        </a>
    
        <div class="table-responsive">
            <table class="table table-striped table-hover align-middle">
                <thead class="table-dark">
                    <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Title</th>
                        <th scope="col">Writer</th>
                        <th scope="col">Category</th>

                        <th scope="col">Description</th>
                        <th scope="col" class="text-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @if (!Model.Any())
                    {
                        <tr>
                            <td colspan="5" class="text-center text-muted">No posts found.</td>
                        </tr>
                    }
                    else
                    {
                        @foreach (var post in Model)
                        {
                            <tr>
                                <td>@post.PostId</td>
                                <td>@post.Title</td>
                                <td>@post.Writer?.Name @post.Writer?.Surname</td>
                                <td>@post.Category?.Name</td>
                                <td>@post.Description</td>
                                <td class="text-center">
                                    <a class="btn btn-warning btn-sm" asp-controller="Post" asp-action="Edit" asp-route-id="@post.PostId">
                                        <i class="fas fa-edit"></i> Edit
                                    </a>
                                    <button class="btn btn-danger btn-sm" onclick="confirmDelete('@post.PostId')">
                                        <i class="fas fa-trash-alt"></i> Delete
                                    </button>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
    
    @section Scripts {
        <!-- SweetAlert2 -->
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        <!-- FontAwesome -->
        <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
        <script>
            function confirmDelete(postId) {
                Swal.fire({
                    title: 'Are you sure?',
                    text: "You won't be able to revert this!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, delete it!'
                }).then((result) => {
                    if (result.isConfirmed) {
                        window.location.href = '/Post/Delete/' + postId;
                    }
                })
            }
        </script>
    }
    